import type { ComboboxOption } from '@/shared/components/Combobox'

export const COMMON_STORES: ComboboxOption[] = [
  { value: 'Albertsons', label: 'Albertsons' },
  { value: 'ALDI', label: 'ALDI' },
  { value: "BJ's Wholesale Club", label: "BJ's Wholesale Club" },
  { value: 'Costco', label: 'Costco' },
  { value: 'Dollar General', label: 'Dollar General' },
  { value: "Farmer's Market", label: "Farmer's Market" },
  { value: 'Fred Meyer', label: 'Fred Meyer' },
  { value: "Fry's Food & Drug", label: "Fry's Food & Drug" },
  { value: 'Giant Food', label: 'Giant Food' },
  { value: 'H-E-B', label: 'H-E-B' },
  { value: 'Harps Food Stores', label: 'Harps Food Stores' },
  { value: 'Hy-Vee', label: 'Hy-Vee' },
  { value: 'King Soopers', label: 'King Soopers' },
  { value: 'Kroger', label: 'Kroger' },
  { value: 'Lidl', label: 'Lidl' },
  { value: "Macey's", label: "Macey's" },
  { value: 'Market Basket', label: 'Market Basket' },
  { value: 'Meijer', label: 'Meijer' },
  { value: 'Natural Grocers', label: 'Natural Grocers' },
  { value: 'Publix', label: 'Publix' },
  { value: 'QFC', label: 'QFC' },
  { value: "Ralph's", label: "Ralph's" },
  { value: 'Randalls', label: 'Randalls' },
  { value: 'Safeway', label: 'Safeway' },
  { value: "Sam's Club", label: "Sam's Club" },
  { value: "Smith's Food & Drug", label: "Smith's Food & Drug" },
  { value: 'Sprouts Farmers Market', label: 'Sprouts Farmers Market' },
  { value: 'Stop & Shop', label: 'Stop & Shop' },
  { value: 'Target', label: 'Target' },
  { value: "Trader Joe's", label: "Trader Joe's" },
  { value: 'Vons', label: 'Vons' },
  { value: 'Walmart', label: 'Walmart' },
  { value: 'Wegmans', label: 'Wegmans' },
  { value: 'Whole Foods Market', label: 'Whole Foods Market' },
  { value: 'WinCo Foods', label: 'WinCo Foods' },
  { value: 'Winn-Dixie', label: 'Winn-Dixie' },
]
